### PR TITLE
bugfix: autocomplete and modifyButton don't work in create success page

### PR DESCRIPTION
**Pull request by micln**
## autocomplete

- autocomplete control could show in this page
- when I copy the success value in box, if I leave the widget immediately, the box will not be null. the form will get the result after the request done.

## modifyButton

- modify button is works.

### CODE REVIEW

**Comment by micln** [comment]
@zhwei 把autocomplete.php 176行改成这个试试

```javascript
complete: function(response){
    response.responseJSON.forEach(function (item) {
        blod_{$this->name}.valueCache[item.{$this->record_label}] = item.{$this->record_id};
    });
    var _label = $.trim($('#auto_{$this->name}').val());
    if ( _label in blod_{$this->name}.valueCache ) {
        $('#{$this->name}').val(blod_{$this->name}.valueCache[_label]);
    }else{
        $('#{$this->name}').val('');
    }
}
```

**Comment by zhwei** [comment]
提PR上来

**Comment by micln** [comment]
还是不对，感觉还是得用他原来的方案

**Comment by micln** [comment]
@zhwei 能先把这个PR去掉么。回滚到上次的版本先

**Comment by zhwei** [comment]
不用，你先修就行

**Pull request closed without merging**
